[workspace]
members = ["client", "json", "jsonrpc"]
exclude = ["integration_test", "regtest"]
resolver = "2"

[patch.crates-io.bitcoind-json-rpc-client]
path = "client"

[patch.crates-io.bitcoind-json-rpc-types]
path = "json"

[patch.crates-io.jsonrpc]
path = "jsonrpc"
